# Generated by Django 4.1 on 2022-09-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'Cor'), ('size', 'Tamanho')], max_length=100),
        ),
    ]
