# Generated by Django 4.1 on 2022-09-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_reviewrating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewrating',
            options={'verbose_name': 'Comentário', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='review',
            field=models.TextField(blank=True, max_length=500, verbose_name='Comentário'),
        ),
    ]
